HAS_ROUND_OF_32 = True

#points: (these are actually not used at the moment but really they should be)
GROUP_STAGE_MATCHES_POINTS = 1
RO32_TEAMS_POINTS = 1
RO16_TEAMS_POINTS = 1
RO8_TEAMS_POINTS = 1
SEMI_FINAL_TEAMS_POINTS = 1
FINAL_TEAMS_POINTS = 2
WINNER_POINTS = 1
HOW_FAR_DANMARK_REACHES_POINTS = 1
TOP_SCORER_POINTS = 2
DANE_TO_SCORE_POINTS = 1
HOW_MANY_GOALS_BY_DANE_POINTS = 1
RED_CARDED_PLAYER_POINTS = 2